spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: 'update'
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/rentalapp
    password: '14289013'
server:
  error:
    include-message: always